### ISSUE TITLE
Declare license

### ISSUE THREAD

**Issue by Freso** [aidanrwt/twitch-bot#10]
Right now the code is not released under any license (that I could find), which means the author has full copyright. Please [declare a license for the code in the repository](https://help.github.com/articles/licensing-a-repository/).

**Comment by gboudrias** [comment]
@aidanrwt I have many contributions to make but I legally cannot. Would you revisit this issue? Is there a something I can do to push it along?

**Comment by aidanrwt** [comment]
This package is no longer maintained whatsoever. You can do whatever you want with any of the code, so feel free to create a pull request including the relevant license.

Apologies for the late reply.
