### ISSUE TITLE
Nonascii characters

### ISSUE THREAD

**Issue by BurntMicah** [aidanrwt/twitch-bot#2]
When people use nonascii characters the bot crashes. I used message = message.encode('ascii', 'ignore')

**Comment by LukeBoland** [comment]
This is also an issue when users have non-ascii characters in their names.

**Comment by Aareon** [comment]
Try message = message.encode('utf-8')

I am about to push an update to bot.py that fixes an issue with !randomemote on machines that do not support ASCII
